FROM golang:1.14-alpine AS build
WORKDIR /go/src
ADD . .

ENV CGO_ENABLED=0
RUN go build -mod=readonly -a -installsuffix cgo -o build/apiserver .

FROM alpine:edge AS runtime
COPY --from=build /go/src/build/api ./
EXPOSE 8080/tcp
ENTRYPOINT ["./api"]
